### PR TITLE
Add ip route for allowed ips

### PR DESCRIPTION
**Pull request by bengtfredh**
wg command do not add ip route for allowed-ips like wg-quick. add command to ad ip route for all networks in allowed-ips.

### CODE REVIEW

**Review by carbogninalberto — APPROVED** [review]

**Comment by carbogninalberto** [comment]
Please merge this @egor-tensin! Thank you very much

**Comment by PabloScolpino** [comment]
👍🏻 for this being merged :-)

**Comment by z0lope0z** [comment]
I need this

**Comment by egor-tensin** [comment]
Sorry, I was in no fit state to deal with my GitHub Actions for the past year. I'll try to keep up in the future.

Released.

**Pull request merged**
